---
title: "R Notebook"
output: html_notebook
---

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.


Loading the state transition matrix: 
```{r}
library(expm)  
mat <- matrix(c(0.1, 0, 0, 1, 0.2, 0, 0, 0, 0.3, 1, 0, 0, 0.4, 0, 1, 0), nrow=4)
```

Matrix multiplication for 7.1.2
```{r}
x0 <- matrix(c(1, 0, 0, 0), nrow=1)
x1 <- x0 %*% mat
x2 <- x1 %*% mat
x3 <- x2 %*% mat
x4 <- x3 %*% mat
x5 <- x4 %*% mat
x6 <- x5 %*% mat
x7 <- x6 %*% mat
x8 <- x7 %*% mat
x9 <- x8 %*% mat
x10 <- x9 %*% mat
```

Output for x1 - x10:
```{r}
x1
x2
x3
x4
x5
x6
x7
x8
x9
x10
```

Matrix powering for 7.1.3
```{r}
mat %^% 32
mat %^% 100
mat %^% 1000
```


Loading new state transition matrix for 7.1.5 and matrix multiplication:

```{r}
mat2 <- matrix(c(0, 0, 0, 1, 0.5, 0, 0, 0, 0, 1, 0, 0, 0.5, 0, 1, 0), nrow=4)
x0 <- matrix(c(1, 0, 0, 0), nrow=1)
x1 <- x0 %*% mat2
x2 <- x1 %*% mat2
x3 <- x2 %*% mat2
x4 <- x3 %*% mat2
x5 <- x4 %*% mat2
x6 <- x5 %*% mat2
x7 <- x6 %*% mat2
x8 <- x7 %*% mat2
x9 <- x8 %*% mat2
x10 <- x9 %*% mat2
```

Output for x1 - x10 for 7.1.5:
```{r}
x1
x2
x3
x4
x5
x6
x7
x8
x9
x10
```

Matrix powering for 7.1.7
```{r}
mat2 %^% 32
mat2 %^% 33
mat2 %^% 34
```

